name: Notifications Archiver
description:
  Automatically marks all notifications for closed issues and pull requests as
  done
author: rentziass

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: archive
  color: purple

# Define your inputs here.
inputs: {}

# Define your outputs here.
outputs: {}

runs:
  using: node20
  main: dist/index.js
